// <auto-generated />
using System;
using Srv.Auth.Repository.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Srv.Auth.Repository.Migrations
{
    [DbContext(typeof(AuthContext))]
    [Migration("20230227133150_001-inicial")]
    partial class _001inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Srv.Auth.Domain.Entities.User", b =>
                {
                    b.Property<string>("CpfCnpj")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.HasKey("CpfCnpj");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);

                    b.HasData(
                        new
                        {
                            CpfCnpj = "12276789751",
                            CriadoEm = new DateTime(2023, 2, 27, 13, 31, 50, 575, DateTimeKind.Utc).AddTicks(477),
                            Email = "thiago.prog@outlook.com",
                            Id = new Guid("990655ae-243a-447d-95b7-c5e8abce3fdb"),
                            Nome = "Thiago Alcantara",
                            Senha = "A574DE14EEEB439CF1CC62B7468A71B8F3E58348B662F96D5590A7490B2DDD5A"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
